[skip ci] Some issues applying the OTA target: esp32c6 Panic after starting to write to OTA Slot0 ``` panicked at /home/jubeor/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/linked_list_allocator-0.10.5/src/hole.rs:554:9: Freed node (0x4081e764) aliases existing hole (0x4080fd5c[73728])! Bad free? ``` running a target with the partitions from partitions.csv
When the current ota slot is 0 and the sftp server receives an OTA it writes it OK to the nand.

After that the program tries to switch to slot 1 and set is as new.

then I perform a esp_hal::system::reset() that works since I can see the rebooting in the serial console

Suspiciously, the build timestamp is identical to the previous boot where it should not.

At that point, when I start another OTA the program panics en storage.write

I will double check if I am writing to the right partition and if the ota partition that I believe that is running is really running