Migrating towards the sunset, first hurdle: getrandom() has no supported esp-hal random function (esp-idf OTOH is supported via https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/random.html#_CPPv415esp_fill_randomPv6size_t, but we don't use IDF)... probably need to define a custom getrandom and point it to esp-hal's rnd. This seems to be known upstream, at least for ESP-IDF, not necessarily for ESP-HAL though∷ https://github.com/rust-random/getrandom/issues/375
Actual error:

   Compiling getrandom v0.2.15
   Compiling embedded-hal-async v1.0.0
error: target is not supported, for more information see: https://docs.rs/getrandom/#unsupported-targets
   --> /Users/rvalls/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.2.15/src/lib.rs:347:9
    |
347 | /         compile_error!("target is not supported, for more information see: \
348 | |                         https://docs.rs/getrandom/#unsupported-targets");
    | |________________________________________________________________________^

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> /Users/rvalls/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.2.15/src/lib.rs:398:9
    |
398 |         imp::getrandom_inner(dest)?;
    |         ^^^ use of undeclared crate or module `imp`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `getrandom` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...